// Generated by Wrangler on Tue Jul 09 2024 09:27:52 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
}
