#:schema node_modules/wrangler/config-schema.json
name = "foodie-delight"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "foodie-delight"
database_id = "b7975fff-3b24-44b6-bfb6-edd92e3bd060"
